### PR TITLE
Allow PHPStan to match with `@throws` phpdoc

### PR DESCRIPTION
**Pull request by rvanlaak**
[PHPStan `0.10` was released last Weekend](https://github.com/phpstan/phpstan/releases/tag/0.10) 🎉 , and will throw the following exception starting from level 2:

> PHPDoc tag @throws with type GuzzleHttp\Exception\GuzzleException is not subtype of Throwable

As all exceptions eventually extend `\RuntimeException`, and as we in userland want to rely on the interface, letting  `GuzzleException` interface extend `\Throwable` would be preferable.

also see #1971

### CODE REVIEW

**Comment by rvanlaak** [comment]
@Nyholm found out that as well, are there plans for Guzzle 7 on `php: ^7.1` ? 

Any idea on how to cover Guzzle under PHPStan `^0.10`? I can imagine that others will start having this problem as well. 

> @throws \GuzzleHttp\Exception\GuzzleException|\RuntimeException

Using the above as phpdoc won't solve the phpstan error either, so the only thing I can think of at the moment is to let PHPStan exclude it 👎 :

```
# phpstan.neon
parameters:
    ignoreErrors:
        - '#PHPDoc tag @throws with type GuzzleHttp\\Exception\\GuzzleException is not subtype of Throwable#'
```

**Comment by Majkl578** [comment]
Note that PHP 5.5 is **dead** for 2 years already. PHP 5.6 and PHP 7.0 are security-only and will die at the end of this year.
Supporting anything below 7.1 is basically non-sense from maintainer's PoV nowadays. You should migrate to fully typehinted PHP 7.1 code. :blush: (Let me know if I can help with this, did quite a lot of similar work on (not only) Doctrine projects.)

**Comment by rvanlaak** [comment]
> The type provided with this tag MUST represent an object of the class Exception or any subclass thereof.

That actually is an interesting one, as all Guzzle's `GuzzleException` implementations actually do. The only thing is that the `GuzzleException` interface itself doesn't 😉

**Comment by Majkl578** [comment]
Yes, that's correct, unfortunately using interfaces that don't extend Throwable was _never_ supported and was merely a _convention_ of some projects.
Anyone can implement such interface in non-Exception/non-Error class, making it basically pointless marker interface.

This was also brought up in the PHPStan PR: https://github.com/phpstan/phpstan/pull/1001#issuecomment-388532164
I personally believe that now, in 2018, it's almost an edge case (and you can simply add one `ignoreErrors` for legacy code) and PHP 5.x code can safely be ignored as it's not a primary target group.
OTOH it already found a bug elsewhere: https://github.com/doctrine/migrations/pull/739/files#diff-f2788aa62fbd5343d8695bd6cff10804L33

File: src/Exception/GuzzleException.php [hunk 1]
```diff
@@ -1,13 +1,4 @@
...
- * @method string getMessage()
- * @method \Throwable|null getPrevious()
- * @method mixed getCode()
- * @method string getFile()
- * @method int getLine()
- * @method array getTrace()
- * @method string getTraceAsString()
- */
-interface GuzzleException {}
+interface GuzzleException extends \Throwable {}
```
Comment (babaorum) [inline src/Exception/GuzzleException.php]: This is not valid in php cf my comment in the issue.

**Comment by Majkl578** [comment]
Ad legacy PHP, see: https://github.com/guzzle/guzzle/pull/2098

**Comment by janedbal** [comment]
The user base won't be left alone. They will still have the 6.x version, don't they? You can still maintain that branch if you want...

**Comment by Majkl578** [comment]
> No, it's non-sense from a consumer point of view. From a maintainer point of view you have to consider the user base (you can't leave them alone), other elements of the roadmap, etc.

Not really true. As a maintainer, you have to maintain compatibility with a huge range of PHP versions. This itself makes things much more complex and greatly increases possibilities of bugs in _some_ PHP versions.

As said by @janedbal, releasing 7.0 with PHP 7.1 requirement does not mean _leaving anyone alone_, you still have 6.x with 5.5 support and bugfixes coming in.

OTOH people stuck on dead PHP versions block whole ecosystem in past.

**Comment by rvanlaak** [comment]
If there would be a date when PSR 18 would get released, then that might be Guzzle 7's release goal? At least, based on https://github.com/guzzle/guzzle/pull/2098#issuecomment-400637989 I assume that would be a solid argument to define the future roadmap? As PSR 18 is still in draft, I don't see this happening within now and 2 years though. @Nyholm any plans on the Readiness vote?

This all doesn't mean work can't get started on a `develop` branch yet. It's most likely that Guzzle wil support PSR 18 asap after it's released, meaning that PHP7 will be the minimum. The remaining now would be to decide whether supporting abandoned versions of PHP is enough reason to formulate a roadmap / date when Guzzle `5.x` would become EOL.

**Comment by Majkl578** [comment]
Sorry, I just don't see any correlation between PSR release and Guzzle 7. Those are two totally different milestones...
Also I absolutely don't understand why some unfinished PSR (with one single-method interface) should block all the work on PHP 7.1 migration?

**Comment by mtdowling** [comment]
Does Drupal still rely on Guzzle? Are they still locked at PHP 5.5 or have they raised their minimum version requirement to 7+?

**Comment by Majkl578** [comment]
How is that relevant?
Can Drupal use Guzzle 6? Yes,
Why should Drupal block evolution of whole ecosystem? Isn't that selfish?

**Comment by wirwolf** [comment]
Psalm send me this error
```
ERROR: InvalidThrow - src/Infrastructure/Query/Http/ProgramQuery.php:67:16 - Class supplied for @throws GuzzleHttp\Exception\GuzzleException does not implement Throwable
     * @throws GuzzleException

```

**Comment by GrahamCampbell** [comment]
Doesn't symfony have a polyfil that will allow this code on PHP 5?

**Comment by rvanlaak** [comment]
> Doesn't symfony have a polyfil that will allow this code on PHP 5?

see https://github.com/symfony/polyfill/issues/101

**Comment by GrahamCampbell** [comment]
Oh, yeh, they only have `Error` polyfilled... https://github.com/symfony/polyfill/blob/master/src/Php70/Resources/stubs/Error.php.

**Comment by rvanlaak** [comment]
@Nyholm fixed this in #2375 so this PR can be closed 👍
